# Generated by Django 3.2.7 on 2021-09-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comapny', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('vacancy', models.IntegerField(blank=True, null=True)),
                ('last_date', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
